const Scenario = NamedTuple{(:name, :two_roots, :needs_git, :steps),
                            Tuple{String,Bool,Bool,Vector{Vector{String}}}}

scenario(name::String, steps; two_roots::Bool=false, needs_git::Bool=false) =
    Scenario((name, two_roots, needs_git, Vector{String}[String.(s) for s in steps]))

const SCENARIOS = Scenario[
    scenario("init", [
        ["init", "--quiet"],
        ["init", "--quiet"],
        ["@2", "init", "--quiet", "--id-stride=4", "--id-offset=1"],
        ["@2", "add", "w", "--type=feature", "--cynefin=clear", "--title=First", "--quiet"],
        ["@2", "add", "w", "--type=feature", "--cynefin=clear", "--title=Second", "--quiet"],
    ]; two_roots=true),
    scenario("add-kinds", [
        ["init", "--quiet"],
        ["add", "g", "--title=Goal", "--quiet"],
        ["add", "y", "--title=Disc", "--tags=auth", "--surface=src/a.jl", "--quiet"],
        ["add", "r", "--title=Retro", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Work", "--quiet"],
        ["add", "d", "--title=Decision", "--quiet"],
        ["add", "q", "--cynefin=clear", "--targets=W-01", "--title=Question", "--quiet"],
        ["add", "b", "--cynefin=clear", "--targets=W-01", "--title=Bet", "--quiet"],
        ["add", "t", "--title=Theme", "--quiet"],
        ["!write", "src/a.jl"],
        ["!append", ".grove/glossary.md", "| auth | a term | test |"],
        ["add", "y", "--title=Discovery", "--tags=auth", "--surface=src/a.jl", "--from=W-01", "--quiet"],
        ["list", "w"],
        ["list", "y"],
        ["check", "--quiet"],
    ]),
    scenario("add-usage-guards", [
        ["init", "--quiet"],
        ["add", "w", "Positional title"],
        ["add", "w"],
        ["add", "w", "--help"],
        ["add"],
        ["add", "w", "--type=bug", "--cynefin=clear", "--title=Real", "--quiet"],
        ["list", "w"],
        ["check", "--quiet"],
    ]),
    scenario("add-g-fitness-required", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=NoFitness", "--area=A-01"],
        ["add", "g", "--title=NoTarget", "--area=A-01", "--fitness-kind=count"],
        ["add", "g", "--title=Manual", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "g", "--title=Legacy", "--area=A-01", "--fitness=1/1"],
        ["add", "g", "--title=Structured", "--area=A-01", "--fitness-kind=count", "--fitness-target=2", "--quiet"],
        ["set", "G-02", "fitness=1/1"],
        ["set", "G-02", "fitness_target=3", "--quiet"],
        ["show", "G-02"],
        ["list", "g"],
        ["check", "--quiet"],
    ]),
    scenario("field-ops", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Work", "--quiet"],
        ["field", "W-01", "ac", "add", "first", "--quiet"],
        ["field", "W-01", "ac", "add", "second", "--quiet"],
        ["field", "W-01", "ac", "rm", "1", "--quiet"],
        ["field", "W-01", "ac", "add", "third", "--quiet"],
        ["field", "W-01", "ac", "clear", "--quiet"],
        ["field", "W-01", "ac", "rm", "1", "--quiet"],
        ["show", "W-01"],
    ]),
    scenario("link-cycle", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--title=One", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--title=Two", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--title=Three", "--quiet"],
        ["link", "W-01", "blocks", "W-02", "--quiet"],
        ["link", "W-02", "blocks", "W-03", "--quiet"],
        ["link", "W-03", "blocks", "W-01", "--quiet"],
        ["link", "G-01", "implements", "W-01", "--quiet"],
        ["unlink", "W-02", "blocks", "W-03", "--quiet"],
        ["link", "W-03", "blocks", "W-01", "--quiet"],
        ["deps", "W-01"],
        ["graph"],
    ]),
    scenario("w-lifecycle", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Migrate", "--fitness-kind=count", "--fitness-target=10", "--area=A-01", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Login", "--quiet"],
        ["field", "W-01", "ac", "add", "login works", "--quiet"],
        ["field", "W-01", "hypothesis", "add", "fewer resets", "--quiet"],
        ["field", "W-01", "evidence_strategy", "add", "run suite", "--quiet"],
        ["fitness", "W-01", "G-01", "+5", "--quiet"],
        ["evidence", "W-01", "login tests green", "--quiet"],
        ["set", "W-01", "status=ready", "--quiet"],
        ["dor", "W-01"],
        ["set", "W-01", "status=progress", "--quiet"],
        ["set", "W-01", "status=done", "--quiet"],
        ["show", "G-01"],
        ["set", "G-01", "fitness_target=5", "--quiet"],
        ["show", "G-01"],
        ["check", "--quiet"],
    ]),
    scenario("dor-refusal", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Work", "--quiet"],
        ["set", "W-01", "status=ready", "--quiet"],
        ["set", "W-01", "status=progress", "--quiet"],
        ["dor", "W-01"],
    ]),
    scenario("wip-i4", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=One", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Two", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Three", "--quiet"],
        ["field", "W-01", "ac", "add", "x", "--quiet"],
        ["field", "W-01", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-01", "evidence_strategy", "add", "x", "--quiet"],
        ["field", "W-02", "ac", "add", "x", "--quiet"],
        ["field", "W-02", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-02", "evidence_strategy", "add", "x", "--quiet"],
        ["field", "W-03", "ac", "add", "x", "--quiet"],
        ["field", "W-03", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-03", "evidence_strategy", "add", "x", "--quiet"],
        ["fitness", "W-01", "G-01", "+1", "--quiet"],
        ["fitness", "W-02", "G-01", "+1", "--quiet"],
        ["fitness", "W-03", "G-01", "+1", "--quiet"],
        ["set", "W-01", "status=ready", "--quiet"],
        ["set", "W-02", "status=ready", "--quiet"],
        ["set", "W-03", "status=ready", "--quiet"],
        ["set", "W-01", "status=progress", "--quiet"],
        ["set", "W-02", "status=progress", "--quiet"],
        ["set", "W-03", "status=progress", "--quiet"],
        ["status"],
    ]),
    scenario("i5-blocks", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--title=Blocker", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Blocked", "--quiet"],
        ["field", "W-02", "ac", "add", "x", "--quiet"],
        ["field", "W-02", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-02", "evidence_strategy", "add", "x", "--quiet"],
        ["fitness", "W-02", "G-01", "+1", "--quiet"],
        ["link", "W-01", "blocks", "W-02", "--quiet"],
        ["set", "W-02", "status=ready", "--quiet"],
        ["set", "W-02", "status=progress", "--quiet"],
        ["set", "W-01", "status=rejected", "--quiet"],
        ["set", "W-02", "status=progress", "--quiet"],
    ]),
    scenario("sessions", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Work", "--quiet"],
        ["field", "W-01", "ac", "add", "x", "--quiet"],
        ["field", "W-01", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-01", "evidence_strategy", "add", "x", "--quiet"],
        ["fitness", "W-01", "G-01", "+1", "--quiet"],
        ["set", "W-01", "status=ready", "--quiet"],
        ["set", "W-01", "status=progress", "--session=alice", "--quiet"],
        ["status", "--session=alice"],
        ["status", "--session=bob"],
        ["resume", "W-01", "--session=bob", "--quiet"],
        ["handoff", "W-01", "--to=carol", "--session=bob", "--quiet"],
        ["handoff", "W-01", "--to=dave", "--session=alice"],
        ["revert", "W-01", "--session=carol", "--quiet"],
        ["status"],
        ["show", "W-01"],
    ]),
    scenario("staging-overwrite", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Count", "--fitness-kind=count", "--fitness-target=2", "--area=A-01", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=TwoStep", "--quiet"],
        ["field", "W-01", "ac", "add", "x", "--quiet"],
        ["field", "W-01", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-01", "evidence_strategy", "add", "x", "--quiet"],
        ["fitness", "W-01", "G-01", "+1", "--quiet"],
        ["fitness", "W-01", "G-01", "+2", "--quiet"],
        ["evidence", "W-01", "first probe", "--quiet"],
        ["evidence", "W-01", "second probe", "--quiet"],
        ["set", "W-01", "status=ready", "--quiet"],
        ["set", "W-01", "status=progress", "--quiet"],
        ["set", "W-01", "status=done", "--quiet"],
        ["show", "G-01"],
        ["show", "W-01"],
    ]),
    scenario("packet-cone", [
        ["init", "--quiet"],
        ["!write", "src/x.jl"],
        ["!append", ".grove/glossary.md", "| auth | a term | test |"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Reliable auth", "--fitness-kind=count", "--fitness-target=5", "--area=A-01", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Auth schema", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Token store", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Login flow", "--surface=src/x.jl", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=SSO login", "--quiet"],
        ["link", "W-01", "blocks", "W-03", "--quiet"],
        ["link", "W-02", "blocks", "W-03", "--quiet"],
        ["link", "W-03", "blocks", "W-04", "--quiet"],
        ["link", "G-01", "blocks", "W-01", "--quiet"],
        ["link", "G-01", "blocks", "W-02", "--quiet"],
        ["add", "y", "--title=Note", "--tags=auth", "--surface=src/x.jl", "--from=W-03", "--quiet"],
        ["set", "Y-01", "status=active", "--quiet"],
        ["packet", "W-03", "--cone"],
        ["packet", "W-04", "--cone"],
        ["packet", "W-04", "--cone", "--cone-depth=1"],
    ]),
    scenario("render-golden", [
        ["init", "--quiet"],
        ["!write", "src/a.jl"],
        ["!append", ".grove/glossary.md", "| auth | a term | test |"],
        ["add", "a", "--title=Core", "--quiet"],
        ["add", "g", "--title=Ship", "--fitness-kind=count", "--fitness-target=1", "--area=A-01", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Feature", "--surface=src/z.jl", "--quiet"],
        ["add", "q", "--cynefin=clear", "--targets=W-01", "--title=Open", "--quiet"],
        ["add", "q", "--cynefin=clear", "--title=Answered", "--quiet"],
        ["field", "Q-02", "outcome", "add", "yes", "--quiet"],
        ["set", "Q-02", "status=answered", "--quiet"],
        ["add", "b", "--cynefin=clear", "--title=Pending", "--quiet"],
        ["add", "b", "--cynefin=clear", "--title=Validated", "--quiet"],
        ["set", "B-02", "status=validated", "--quiet"],
        ["add", "d", "--title=Accepted", "--quiet"],
        ["set", "D-01", "status=accepted", "--quiet"],
        ["add", "y", "--title=Note", "--tags=auth", "--surface=src/a.jl", "--from=W-01", "--quiet"],
        ["set", "Y-01", "status=active", "--quiet"],
        ["render", "--quiet"],
        ["!cat", ".grove/index.md"],
    ]),
    scenario("discovery-lifecycle", [
        ["init", "--quiet"],
        ["!write", "src/a.jl"],
        ["!write", "src/b.jl"],
        ["!append", ".grove/glossary.md", "| auth | a term | test |"],
        ["add", "w", "--type=spike", "--cynefin=clear", "--title=Spike", "--quiet"],
        ["add", "y", "--title=AuthNote", "--tags=auth", "--surface=src/a.jl", "--from=W-01", "--quiet"],
        ["add", "y", "--title=Second", "--tags=auth", "--surface=src/b.jl", "--from=W-01", "--quiet"],
        ["field", "Y-02", "tags", "clear", "--quiet"],
        ["set", "Y-02", "status=active", "--quiet"],
        ["field", "Y-02", "tags", "add", "auth", "--quiet"],
        ["set", "Y-01", "status=active", "--quiet"],
        ["check", "--quiet"],
        ["!rm", "src/a.jl"],
        ["check", "--quiet"],
        ["set", "Y-01", "status=stale", "--quiet"],
        ["check", "--quiet"],
        ["revalidate", "Y-01", "--surface=src/b.jl", "--quiet"],
        ["show", "Y-01"],
        ["set", "Y-01", "status=superseded", "--quiet"],
        ["set", "Y-01", "status=active", "--quiet"],
        ["check", "--quiet"],
    ]),
    scenario("distill-archive", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--fitness-kind=count", "--fitness-target=1", "--area=A-01", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Work", "--quiet"],
        ["field", "W-01", "ac", "add", "x", "--quiet"],
        ["field", "W-01", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-01", "evidence_strategy", "add", "x", "--quiet"],
        ["fitness", "W-01", "G-01", "+1", "--quiet"],
        ["evidence", "W-01", "e", "--quiet"],
        ["set", "W-01", "status=ready", "--quiet"],
        ["set", "W-01", "status=progress", "--quiet"],
        ["set", "W-01", "status=done", "--quiet"],
        ["add", "b", "--title=Bench", "--cynefin=clear", "--quiet"],
        ["add", "q", "--title=Quest", "--cynefin=clear", "--quiet"],
        ["add", "d", "--title=Dec", "--quiet"],
        ["link", "W-01", "produces", "B-01", "--quiet"],
        ["link", "W-01", "produces", "Q-01", "--quiet"],
        ["link", "W-01", "produces", "D-01", "--quiet"],
        ["set", "B-01", "status=validated", "--quiet"],
        ["set", "Q-01", "status=answered", "--quiet"],
        ["set", "D-01", "status=accepted", "--quiet"],
        ["distill", "G-01"],
        ["archive", "G-01"],
        ["distill", "G-01", "--null", "--quiet"],
        ["archive", "G-01", "--quiet"],
        ["check", "--quiet"],
    ]),
    scenario("glossary-undo", [
        ["init", "--quiet"],
        ["!write", "src/a.jl"],
        ["!append", ".grove/glossary.md", "| auth | a term | test |"],
        ["!append", ".grove/glossary.md", "| seam | another term | test |"],
        ["add", "w", "--type=spike", "--cynefin=clear", "--title=Spike", "--quiet"],
        ["add", "y", "--title=Note", "--tags=auth,seam", "--surface=src/a.jl", "--from=W-01", "--quiet"],
        ["glossary", "rename", "auth", "identity", "--quiet"],
        ["!cat", ".grove/glossary.md"],
        ["show", "Y-01"],
        ["undo", "--quiet"],
        ["!cat", ".grove/glossary.md"],
        ["show", "Y-01"],
        ["check", "--quiet"],
    ]),
    scenario("undo-sequence", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Work", "--quiet"],
        ["set", "W-01", "cynefin=complicated", "--quiet"],
        ["field", "W-01", "ac", "add", "first", "--quiet"],
        ["show", "W-01"],
        ["undo", "--quiet"],
        ["show", "W-01"],
        ["undo", "--quiet"],
        ["show", "W-01"],
        ["undo", "--steps=2", "--quiet"],
        ["show", "W-01"],
        ["list", "g"],
        ["check", "--quiet"],
    ]),
    scenario("stats-scripted", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--fitness-kind=count", "--fitness-target=1", "--area=A-01", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Work", "--quiet"],
        ["set", "W-01", "status=progress", "--quiet"],
        ["field", "W-01", "ac", "add", "x", "--quiet"],
        ["field", "W-01", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-01", "evidence_strategy", "add", "x", "--quiet"],
        ["fitness", "W-01", "G-01", "+1", "--quiet"],
        ["set", "W-01", "status=ready", "--quiet"],
        ["set", "W-01", "status=progress", "--quiet"],
        ["evidence", "W-01", "e", "--quiet"],
        ["set", "W-01", "status=done", "--quiet"],
        ["gate", "--quiet"],
        ["!retime-journal"],
        ["stats"],
        ["stats", "--json"],
    ]),
    scenario("promote", [
        ["init", "--quiet"],
        ["@2", "init", "--quiet"],
        ["!write", "src/auth.jl"],
        ["!append", ".grove/glossary.md", "| auth | source term | test |"],
        ["!append", ".grove/glossary.md", "| seams | source term | test |"],
        ["add", "d", "--title=Ctx", "--quiet"],
        ["add", "y", "--title=AuthNote", "--tags=auth,seams", "--surface=src/auth.jl", "--from=D-01", "--quiet"],
        ["promote", "Y-01", "--to={root2}", "--json", "--quiet"],
        ["promote", "Y-01", "--to={root2}", "--quiet"],
        ["@2", "!write", "src/auth.jl"],
        ["@2", "check", "--quiet"],
        ["@2", "!cat", ".grove/glossary.md"],
        ["@2", "show", "Y-01"],
        ["@2", "undo", "--quiet"],
        ["@2", "check", "--quiet"],
        ["check", "--quiet"],
    ]; two_roots=true),
    scenario("renumber", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Alpha", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--title=Beta", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Gamma", "--quiet"],
        ["fitness", "W-01", "G-01", "+2", "--quiet"],
        ["renumber", "G-01", "--to=G-90", "--quiet"],
        ["show", "W-01"],
        ["field", "W-03", "ac", "add", "x", "--quiet"],
        ["field", "W-03", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-03", "evidence_strategy", "add", "x", "--quiet"],
        ["fitness", "W-03", "G-90", "+1", "--quiet"],
        ["evidence", "W-03", "shipped with W-02", "--quiet"],
        ["set", "W-03", "status=ready", "--quiet"],
        ["set", "W-03", "status=progress", "--quiet"],
        ["set", "W-03", "status=done", "--quiet"],
        ["renumber", "W-02", "--to=W-77", "--quiet"],
        ["check", "--quiet"],
    ]),
    scenario("triage", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=G1", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "g", "--title=G2", "--area=A-01", "--fitness-kind=manual", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=NoSurface", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=ZeroCov", "--surface=src/z.jl", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=FullCovOpenQ", "--surface=src/a.jl", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-02", "--title=Fragile", "--surface=src/a.jl", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-02", "--title=Clean", "--surface=src/a.jl", "--quiet"],
        ["add", "q", "--cynefin=complicated", "--targets=W-02", "--title=QZero", "--quiet"],
        ["add", "q", "--cynefin=complicated", "--targets=W-03", "--title=QFull", "--quiet"],
        ["add", "y", "--title=Discovery", "--tags=auth", "--surface=src/a.jl", "--from=W-03", "--quiet"],
        ["set", "Y-01", "status=active", "--quiet"],
        ["field", "W-03", "ac", "add", "x", "--quiet"],
        ["field", "W-03", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-03", "evidence_strategy", "add", "x", "--quiet"],
        ["field", "W-04", "ac", "add", "x", "--quiet"],
        ["field", "W-04", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-04", "evidence_strategy", "add", "x", "--quiet"],
        ["field", "W-05", "ac", "add", "x", "--quiet"],
        ["field", "W-05", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-05", "evidence_strategy", "add", "x", "--quiet"],
        ["fitness", "W-03", "G-01", "+1", "--quiet"],
        ["fitness", "W-04", "G-02", "+1", "--quiet"],
        ["fitness", "W-05", "G-02", "+1", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--title=PathA", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--title=PathB", "--quiet"],
        ["link", "G-02", "blocks", "W-06", "--quiet"],
        ["link", "G-02", "blocks", "W-07", "--quiet"],
        ["link", "W-06", "blocks", "W-04", "--quiet"],
        ["link", "W-06", "blocks", "W-05", "--quiet"],
        ["link", "W-07", "blocks", "W-05", "--quiet"],
        ["set", "W-06", "status=rejected", "--quiet"],
        ["set", "W-07", "status=rejected", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--title=DoneW", "--quiet"],
        ["evidence", "W-08", "shipped", "--quiet"],
        ["set", "W-08", "status=done", "--quiet"],
        ["triage"],
        ["triage", "--json"],
    ]),
    scenario("check-foreign-status", [
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["!append", ".grove/state.lock", "a A-02 status=archived \"Corrupt\""],
        ["check", "--quiet"],
    ]),
    scenario("check-y-archive", [
        ["init", "--quiet"],
        ["!append", ".grove/state.lock", ":archive"],
        ["!append", ".grove/state.lock", "y Y-99 status=active \"Corrupt\""],
        ["check", "--quiet"],
    ]),
    scenario("help", [
        ["help"],
        ["bogus"],
    ]),
    scenario("gate", [
        ["!git", "init", "-q"],
        ["!write", "a.txt", "a"],
        ["!git", "add", "a.txt"],
        ["!git", "-c", "user.email=t@example.com", "-c", "user.name=t", "commit", "-q", "-m", "scaffold"],
        ["init", "--quiet"],
        ["add", "a", "--title=Area", "--quiet"],
        ["add", "g", "--title=Goal", "--fitness-kind=count", "--fitness-target=1", "--area=A-01", "--quiet"],
        ["add", "w", "--type=feature", "--cynefin=clear", "--goals=G-01", "--title=Work", "--quiet"],
        ["field", "W-01", "ac", "add", "x", "--quiet"],
        ["field", "W-01", "hypothesis", "add", "x", "--quiet"],
        ["field", "W-01", "evidence_strategy", "add", "x", "--quiet"],
        ["fitness", "W-01", "G-01", "+1", "--quiet"],
        ["evidence", "W-01", "e", "--quiet"],
        ["set", "W-01", "status=ready", "--quiet"],
        ["set", "W-01", "status=progress", "--quiet"],
        ["set", "W-01", "status=done", "--quiet"],
        ["field", "W-01", "surface", "add", "a.txt", "--quiet"],
        ["!write", "a.txt", "a2"],
        ["!write", "b.txt", "b"],
        ["!git", "add", "a.txt", "b.txt"],
        ["!git", "-c", "user.email=t@example.com", "-c", "user.name=t", "commit", "-q", "-m", "touch b for W-01"],
        ["!sleep", "2"],
        ["gate", "--theta=0"],
        ["gate", "--theta=0"],
    ]; needs_git=true),
]
