mod common;
#[allow(unused_imports)]
use common::*;
use grove_core::*;
use std::path::PathBuf;

const INIT_GLOSSARY: &str = "# Glossary\n\n| Term | Definition | Source |\n| --- | --- | --- |\n";

fn tmpdir(tag: &str) -> PathBuf {
    let d = std::env::temp_dir().join(format!(
        "grove-core-rtest-{}-{}-{}",
        std::process::id(),
        tag,
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir_all(&d).unwrap();
    d
}

#[test]
fn golden_render_corpus() {
    let sc = corpus_json("render-golden");
    let n = scenario_len(&sc);
    let st = parse_fixture(&step_field(&sc, n - 1, "lock")).unwrap();
    let expected = step_field(&sc, n - 1, "stdout");
    assert_eq!(render_index(&st, 0), expected);
}

#[test]
fn golden_decay_render() {
    let sc = corpus_json("decay-render");
    let n = scenario_len(&sc);
    let st = parse_fixture(&step_field(&sc, n - 1, "lock")).unwrap();
    let expected = step_field(&sc, n - 1, "stdout");
    assert_eq!(render_index(&st, 1), expected);
}

#[test]
fn decay_count_and_lines_feed_render() {
    let d = tmpdir("decay");
    let mut st = State::default();
    let mut y = plain(Kind::Y, "Y-01", "active");
    y.title = "Note".to_string();
    reflist(&mut y, "surface", &["src/dead.jl", "src/live.jl"]);
    reflist(&mut y, "tags", &["auth", "lost"]);
    put(&mut st, y);
    put(&mut st, plain(Kind::D, "D-01", "accepted"));
    edge(&mut st, "Y-01", "distills", "D-01");
    st.edges.last_mut().unwrap().t_created = Some("2031-01-01T00:00:00Z".to_string());
    let ctx = CliCtx::new(d.to_string_lossy().into_owned());
    std::fs::create_dir_all(ctx.devdir()).unwrap();
    std::fs::write(
        ctx.glossarypath(),
        format!("{INIT_GLOSSARY}| auth | a term | test |\n"),
    )
    .unwrap();
    std::fs::create_dir_all(d.join("src")).unwrap();
    std::fs::write(d.join("src/live.jl"), "live\n").unwrap();
    atomic_write_same_dir(&ctx.lockpath(), &serialize(&st)).unwrap();
    let st = match load(&ctx, true) {
        Ok(s) => s,
        Err(e) => panic!("load failed: code={} err={}", e.code, e.err),
    };
    assert_eq!(dashboard_decay_count(&ctx, &st), 1);
    let errs = discovery_decay_errors(&st, &ctx.root, &ctx.glossarypath());
    assert_eq!(
        errs,
        vec![
            "decay: Y-01 dead surface: src/dead.jl".to_string(),
            "decay: Y-01 lost glossary term: lost".to_string(),
        ]
    );
    let idx = render_index(&st, 1);
    assert!(idx.contains("| Decay | 1 | Discovery with decay signals |"));
}

#[test]
fn empty_state_index_shape() {
    let st = State::default();
    let idx = render_index(&st, 0);
    let expected = concat!(
        "<!-- AUTO-GENERATED by grove. Do not edit. Run `grove render` to refresh. -->\n",
        "\n",
        "# Development dashboard\n",
        "\n",
        "## Content health\n",
        "\n",
        "| Measure | Count | Composition |\n",
        "| --- | --- | --- |\n",
        "| C (content) | 0 | validated B 0 \u{b7} answered Q 0 \u{b7} accepted D 0 |\n",
        "| V (uncertainty) | 0 | open Q 0 \u{b7} pending B 0 \u{b7} W below DoR 0 |\n",
        "\n",
        "## Dependency graph\n",
        "\n",
        "```mermaid\n",
        "graph TD\n",
        "classDef area fill:#5a1e4a,color:#fff\n",
        "classDef goal fill:#1e3a5f,color:#fff\n",
        "classDef theme fill:#2a4a3a,color:#fff\n",
        "classDef decision fill:#5a4a1e,color:#fff\n",
        "classDef question fill:#5a3a1e,color:#fff\n",
        "classDef assumption fill:#4a2d5a,color:#fff\n",
        "classDef spike fill:#3a3a5a,color:#fff\n",
        "classDef feature fill:#1e4a4a,color:#fff\n",
        "classDef ready fill:#2d5a27,color:#fff\n",
        "classDef progress fill:#3a4a6a,color:#fff,stroke:#fff,stroke-width:2px\n",
        "classDef done fill:#2d5a27,color:#fff,stroke:#fff,stroke-width:2px\n",
        "classDef rejected fill:#5a5a5a,color:#fff\n",
        "classDef discovery fill:#1f4e5f,color:#fff\n",
        "classDef critical stroke:#ff0,stroke-width:3px\n",
        "```\n",
        "\n",
    );
    assert_eq!(idx, expected);
    assert!(!idx.contains(" critical\n"));
    let gs = render_graph_section(&st);
    assert!(idx.ends_with(&gs));
    assert!(gs.starts_with("## Dependency graph\n"));
    assert!(gs.ends_with("```\n\n"));
}

#[test]
fn decay_rotted_origin_lines() {
    let mut st = State::default();
    let mut y = plain(Kind::Y, "Y-01", "active");
    y.title = "Note".to_string();
    put(&mut st, y);
    put(&mut st, plain(Kind::D, "D-01", "superseded"));
    put(&mut st, plain(Kind::B, "B-01", "invalidated_blocking"));
    edge(&mut st, "Y-01", "distills", "D-01");
    edge(&mut st, "Y-01", "distills", "B-01");
    let d = tmpdir("rotted");
    let gpath = d.join("glossary.md");
    let errs = discovery_decay_errors(&st, &d.to_string_lossy(), &gpath);
    assert_eq!(
        errs,
        vec![
            "decay: Y-01 rotted origin: D-01 (superseded)".to_string(),
            "decay: Y-01 rotted origin: B-01 (invalidated_blocking)".to_string(),
        ]
    );
}

#[test]
fn cmd_render_writes_index_bytes() {
    let d = tmpdir("cmd-render");
    let ctx = CliCtx::new(d.to_string_lossy().into_owned());
    std::fs::create_dir_all(ctx.devdir()).unwrap();
    let mut st = State::default();
    let mut g = plain(Kind::G, "G-01", "unverified");
    g.title = "Ship".to_string();
    put(&mut st, g);
    atomic_write_same_dir(&ctx.lockpath(), &serialize(&st)).unwrap();
    let r = cmd_render(&ctx, &[], &[]);
    assert_eq!(r.code, EXIT_OK);
    let st2 = load(&ctx, true).ok().expect("load failed");
    let bytes = std::fs::read_to_string(ctx.indexpath()).unwrap();
    assert_eq!(bytes, render_index(&st2, 0));
}
