use crate::cli::{atomic_write_same_dir, load, CliCtx};
use crate::decay::dashboard_decay_count;
use crate::model::{Kind, Node, State};
use crate::ops::OpResult;
use crate::status::{is_terminal, listnodes};
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

const INDEX_BANNER: &str =
    "<!-- AUTO-GENERATED by grove. Do not edit. Run `grove render` to refresh. -->";

const CLASSDEF_BLOCK: &str = "classDef area fill:#5a1e4a,color:#fff\n\
classDef goal fill:#1e3a5f,color:#fff\n\
classDef theme fill:#2a4a3a,color:#fff\n\
classDef decision fill:#5a4a1e,color:#fff\n\
classDef question fill:#5a3a1e,color:#fff\n\
classDef assumption fill:#4a2d5a,color:#fff\n\
classDef spike fill:#3a3a5a,color:#fff\n\
classDef feature fill:#1e4a4a,color:#fff\n\
classDef ready fill:#2d5a27,color:#fff\n\
classDef progress fill:#3a4a6a,color:#fff,stroke:#fff,stroke-width:2px\n\
classDef done fill:#2d5a27,color:#fff,stroke:#fff,stroke-width:2px\n\
classDef rejected fill:#5a5a5a,color:#fff\n\
classDef discovery fill:#1f4e5f,color:#fff\n\
classDef critical stroke:#ff0,stroke-width:3px\n";

fn health_tally(
    c: &mut BTreeMap<&'static str, i64>,
    v: &mut BTreeMap<&'static str, i64>,
    st: &State,
    n: &crate::model::Node,
) {
    match n.kind {
        Kind::Q => {
            if n.status == "open" {
                *v.entry("q").or_insert(0) += 1;
            }
            if n.status == "answered" {
                *c.entry("q").or_insert(0) += 1;
            }
        }
        Kind::B => {
            if n.status == "proposed" || n.status == "testing" {
                *v.entry("b").or_insert(0) += 1;
            }
            if n.status == "validated" {
                *c.entry("b").or_insert(0) += 1;
            }
        }
        Kind::D => {
            if n.status == "accepted" {
                *c.entry("d").or_insert(0) += 1;
            }
        }
        Kind::Y => {
            if n.status == "active" {
                *c.entry("y").or_insert(0) += 1;
            }
        }
        Kind::W => {
            if !is_terminal(Kind::W, &n.status) {
                if !crate::dor::dor(st, n, false) {
                    *v.entry("w").or_insert(0) += 1;
                }
                if !n.lines("surface").is_empty() {
                    let (cov, _, _) = crate::algebra::coverage(st, n);
                    if cov < 1.0 {
                        *v.entry("surf").or_insert(0) += 1;
                    }
                }
            }
        }
        _ => {}
    }
}

pub fn content_health(st: &State) -> (BTreeMap<&'static str, i64>, BTreeMap<&'static str, i64>) {
    let mut c: BTreeMap<&'static str, i64> = [("b", 0), ("q", 0), ("d", 0), ("y", 0)].into();
    let mut v: BTreeMap<&'static str, i64> = [("q", 0), ("b", 0), ("w", 0)].into();
    for n in st.nodes.values() {
        if n.archived {
            continue;
        }
        health_tally(&mut c, &mut v, st, n);
    }
    (c, v)
}

pub fn content_health_sums(st: &State) -> (i64, i64) {
    let (c, v) = content_health(st);
    (c.values().sum(), v.values().sum())
}

fn area_health(st: &State, z: &Node) -> (BTreeMap<&'static str, i64>, BTreeMap<&'static str, i64>) {
    let mut c: BTreeMap<&'static str, i64> = [("b", 0), ("q", 0), ("d", 0), ("y", 0)].into();
    let mut v: BTreeMap<&'static str, i64> = [("q", 0), ("b", 0), ("w", 0)].into();
    for id in crate::algebra::area_node_ids(st, z) {
        if let Some(n) = st.nodes.get(&id) {
            health_tally(&mut c, &mut v, st, n);
        }
    }
    c.insert("y", crate::algebra::area_relevant_discoveries(st, z).len() as i64);
    (c, v)
}

fn tally(m: &BTreeMap<&'static str, i64>, k: &str) -> i64 {
    *m.get(k).unwrap_or(&0)
}

fn health_parts(
    c: &BTreeMap<&'static str, i64>,
    v: &BTreeMap<&'static str, i64>,
) -> (String, String) {
    let mut c_parts = vec![
        format!("validated B {}", tally(c, "b")),
        format!("answered Q {}", tally(c, "q")),
        format!("accepted D {}", tally(c, "d")),
    ];
    if tally(c, "y") > 0 {
        c_parts.push(format!("active Discovery {}", tally(c, "y")));
    }
    let mut v_parts = vec![
        format!("open Q {}", tally(v, "q")),
        format!("pending B {}", tally(v, "b")),
        format!("W below DoR {}", tally(v, "w")),
    ];
    let surf = tally(v, "surf");
    if surf > 0 {
        v_parts.push(format!("uncovered surface {surf}"));
    }
    (c_parts.join(" \u{b7} "), v_parts.join(" \u{b7} "))
}

fn sorted_edge_targets(st: &State, label: &str, from: &str) -> Vec<String> {
    let mut out: Vec<String> = st
        .edges
        .iter()
        .filter(|e| e.label == label && e.from == from)
        .map(|e| e.to.clone())
        .collect();
    out.sort();
    out.dedup();
    out
}

fn render_content_health(out: &mut String, st: &State, decay: i64) {
    let (c, v) = content_health(st);
    let (cj, vj) = health_parts(&c, &v);
    let csum: i64 = c.values().sum();
    let vsum: i64 = v.values().sum();
    out.push_str("## Content health\n\n");
    out.push_str("| Measure | Count | Composition |\n");
    out.push_str("| --- | --- | --- |\n");
    out.push_str(&format!("| C (content) | {csum} | {cj} |\n"));
    out.push_str(&format!("| V (uncertainty) | {vsum} | {vj} |\n"));
    if decay > 0 {
        out.push_str(&format!(
            "| Decay | {decay} | Discovery with decay signals |\n"
        ));
    }
    out.push('\n');
}

fn render_areas(out: &mut String, st: &State) {
    let rows = listnodes(st, Kind::A, false);
    if rows.is_empty() {
        return;
    }
    out.push_str("## Areas\n\n");
    out.push_str("| Area | Title | C (content) | V (uncertainty) | Composition |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for z in rows {
        let (c, v) = area_health(st, z);
        let (cj, vj) = health_parts(&c, &v);
        let comp = format!("C: {cj}; V: {vj}");
        let title = if z.title.is_empty() {
            "\u{2013}"
        } else {
            z.title.as_str()
        };
        let csum: i64 = c.values().sum();
        let vsum: i64 = v.values().sum();
        out.push_str(&format!(
            "| {} | {title} | {csum} | {vsum} | {comp} |\n",
            z.id
        ));
    }
    out.push('\n');
    out.push_str("> Relevance view, not a partition: a node touching two areas counts in both; a W without goals counts in none. The Content health totals above are primary.\n");
    out.push('\n');
}

fn render_goals(out: &mut String, st: &State) {
    let rows = listnodes(st, Kind::G, false);
    if rows.is_empty() {
        return;
    }
    out.push_str("## Goals\n\n");
    out.push_str("| ID | Outcome | Fitness function | Status |\n");
    out.push_str("| --- | --- | --- | --- |\n");
    for n in rows {
        let f = crate::fitness::goal_fitness_table_cell(n);
        out.push_str(&format!(
            "| {} | {} | {f} | {} |\n",
            n.id, n.title, n.status
        ));
    }
    out.push('\n');
}

fn render_work(out: &mut String, st: &State) {
    let rows = listnodes(st, Kind::W, false);
    if rows.is_empty() {
        return;
    }
    let cp: BTreeSet<String> = crate::algebra::critical_path(st).into_iter().collect();
    out.push_str("## Work items\n\n");
    out.push_str("| ID | Type | Title | Goals | Cynefin | DoR | Status | Critical |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- | --- | --- |\n");
    for n in rows {
        let gs = n.lines("goals").join(", ");
        let do_r = if crate::dor::dor(st, n, false) {
            "\u{22a4}"
        } else {
            "\u{22a5}"
        };
        let crit = if cp.contains(&n.id) { "\u{2605}" } else { "" };
        let wt = n.wtype.as_deref().unwrap_or("nothing");
        let cy = n.cynefin.as_deref().unwrap_or("nothing");
        out.push_str(&format!(
            "| {} | {wt} | {} | {gs} | {cy} | {do_r} | {} | {crit} |\n",
            n.id, n.title, n.status
        ));
    }
    out.push('\n');
}

fn render_decisions(out: &mut String, st: &State) {
    let rows = listnodes(st, Kind::D, false);
    if rows.is_empty() {
        return;
    }
    out.push_str("## Decisions\n\n");
    out.push_str("| ID | Title | Status | Supersedes |\n");
    out.push_str("| --- | --- | --- | --- |\n");
    for n in rows {
        let sup = sorted_edge_targets(st, "supersedes", &n.id).join(", ");
        out.push_str(&format!(
            "| {} | {} | {} | {sup} |\n",
            n.id, n.title, n.status
        ));
    }
    out.push('\n');
}

fn render_questions(out: &mut String, st: &State) {
    let rows = listnodes(st, Kind::Q, false);
    if rows.is_empty() {
        return;
    }
    out.push_str("## Open questions\n\n");
    out.push_str("| ID | Question | Cynefin | Targets | Status |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for n in rows {
        let t = sorted_edge_targets(st, "asks", &n.id).join(", ");
        let cy = n.cynefin.as_deref().unwrap_or("nothing");
        out.push_str(&format!(
            "| {} | {} | {cy} | {t} | {} |\n",
            n.id, n.title, n.status
        ));
    }
    out.push('\n');
}

fn render_assumptions(out: &mut String, st: &State) {
    let rows = listnodes(st, Kind::B, false);
    if rows.is_empty() {
        return;
    }
    out.push_str("## Assumptions\n\n");
    out.push_str("| ID | Assumption | Tests | Targets | Status |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for n in rows {
        let ts = sorted_edge_targets(st, "tests", &n.id).join(", ");
        let tg = sorted_edge_targets(st, "targets", &n.id).join(", ");
        out.push_str(&format!(
            "| {} | {} | {ts} | {tg} | {} |\n",
            n.id, n.title, n.status
        ));
    }
    out.push('\n');
}

fn render_themes(out: &mut String, st: &State) {
    let rows = listnodes(st, Kind::T, false);
    if rows.is_empty() {
        return;
    }
    out.push_str("## Themes\n\n");
    out.push_str("| ID | Title | Status | Causes work | Themed work |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for n in rows {
        let cw = sorted_edge_targets(st, "causes", &n.id).join(", ");
        let mut tw_ids: Vec<String> = listnodes(st, Kind::W, false)
            .into_iter()
            .filter(|w| w.single("theme").trim() == n.id)
            .map(|w| w.id.clone())
            .collect();
        tw_ids.sort();
        let tw = tw_ids.join(", ");
        let cw = if cw.is_empty() { "\u{2013}".to_string() } else { cw };
        let tw = if tw.is_empty() { "\u{2013}".to_string() } else { tw };
        out.push_str(&format!(
            "| {} | {} | {} | {cw} | {tw} |\n",
            n.id, n.title, n.status
        ));
    }
    out.push('\n');
}

fn render_discoveries(out: &mut String, st: &State) {
    let rows = listnodes(st, Kind::Y, false);
    if rows.is_empty() {
        return;
    }
    out.push_str("## Discoveries\n\n");
    out.push_str("| ID | Title | Tags | Status |\n");
    out.push_str("| --- | --- | --- | --- |\n");
    for n in rows {
        let mut tags = n.lines("tags");
        tags.sort();
        let tags = tags.join(", ");
        out.push_str(&format!(
            "| {} | {} | {tags} | {} |\n",
            n.id, n.title, n.status
        ));
    }
    out.push('\n');
}

fn node_class(n: &Node) -> &'static str {
    match n.kind {
        Kind::G => "goal",
        Kind::A => "area",
        Kind::D => "decision",
        Kind::Q => "question",
        Kind::B => "assumption",
        Kind::T => "theme",
        Kind::Y => "discovery",
        Kind::W => {
            if n.wtype.as_deref() == Some("spike") {
                "spike"
            } else if n.status == "done" || n.status == "archived" {
                "done"
            } else if n.status == "progress" {
                "progress"
            } else if n.status == "ready" {
                "ready"
            } else if n.status == "rejected" {
                "rejected"
            } else {
                "feature"
            }
        }
    }
}

fn mermaid_safe(id: &str) -> String {
    id.replace('-', "_")
}

fn mermaid_edge_line(from: &str, to: &str, label: &str) -> String {
    let f = mermaid_safe(from);
    let t = mermaid_safe(to);
    match label {
        "blocks" => format!("  {f} ==>|{label}| {t}"),
        "targets" => format!("  {f} -.->|{label}| {t}"),
        _ => format!("  {f} -->|{label}| {t}"),
    }
}

fn render_graph(out: &mut String, st: &State) {
    out.push_str("## Dependency graph\n\n");
    out.push_str("```mermaid\n");
    out.push_str("graph TD\n");
    let cp: BTreeSet<String> = crate::algebra::critical_path(st).into_iter().collect();
    for kind in Kind::ALL {
        for n in listnodes(st, kind, false) {
            let label = n.title.replace('"', "'");
            let cls = node_class(n);
            let mut line = format!(
                "  {}[\"{}: {label}\"]:::{cls}",
                mermaid_safe(&n.id),
                n.id
            );
            if cp.contains(&n.id) {
                line.push_str(",critical");
            }
            out.push_str(&line);
            out.push('\n');
        }
    }
    let mut edges: Vec<&crate::model::Edge> = st.edges.iter().collect();
    edges.sort_by(|a, b| (&a.from, &a.label, &a.to).cmp(&(&b.from, &b.label, &b.to)));
    for e in edges {
        if !(st.nodes.contains_key(&e.from) && st.nodes.contains_key(&e.to)) {
            continue;
        }
        out.push_str(&mermaid_edge_line(&e.from, &e.to, &e.label));
        out.push('\n');
    }
    if !cp.is_empty() {
        let ids: Vec<String> = cp.iter().map(|id| mermaid_safe(id)).collect();
        out.push_str(&format!("  class {} critical\n", ids.join(",")));
    }
    out.push_str(CLASSDEF_BLOCK);
    out.push_str("```\n\n");
}

pub fn render_index(st: &State, decay: i64) -> String {
    let mut out = String::new();
    out.push_str(INDEX_BANNER);
    out.push_str("\n\n# Development dashboard\n\n");
    render_content_health(&mut out, st, decay);
    render_areas(&mut out, st);
    render_goals(&mut out, st);
    render_work(&mut out, st);
    render_decisions(&mut out, st);
    render_questions(&mut out, st);
    render_assumptions(&mut out, st);
    render_themes(&mut out, st);
    render_discoveries(&mut out, st);
    render_graph(&mut out, st);
    out
}

pub fn render_graph_section(st: &State) -> String {
    let mut out = String::new();
    render_graph(&mut out, st);
    out
}

pub fn write_index(path: &Path, st: &State, decay: i64) {
    let _ = atomic_write_same_dir(path, &render_index(st, decay));
}

pub fn cmd_render(ctx: &CliCtx, _pos: &[String], _kw: &[(String, String)]) -> OpResult {
    let st = match load(ctx, true) {
        Ok(s) => s,
        Err(e) => return e,
    };
    write_index(&ctx.indexpath(), &st, dashboard_decay_count(ctx, &st));
    OpResult::ok()
}
